[project]
name = "simple-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pravin Vegare", email = "vegarep88@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "openai-agents>=0.22.2",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.52.4",
]

[project.scripts]
simple-ai = "simple_ai:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
